var annotated_dup =
[
    [ "boost", "namespaceboost.html", [
      [ "sinks", "namespaceboost_1_1sinks.html", [
        [ "synchronous_sink", "namespaceboost_1_1sinks.html#classboost_1_1sinks_1_1synchronous__sink", null ]
      ] ],
      [ "hash< boost::asio::ip::address >", "structboost_1_1hash_3_01boost_1_1asio_1_1ip_1_1address_01_4.html", "structboost_1_1hash_3_01boost_1_1asio_1_1ip_1_1address_01_4" ],
      [ "hash<::sgns::endpoint >", "structboost_1_1hash_3_1_1sgns_1_1endpoint_01_4.html", "structboost_1_1hash_3_1_1sgns_1_1endpoint_01_4" ],
      [ "hash<::sgns::tcp_endpoint >", "structboost_1_1hash_3_1_1sgns_1_1tcp__endpoint_01_4.html", "structboost_1_1hash_3_1_1sgns_1_1tcp__endpoint_01_4" ]
    ] ],
    [ "sgns", "namespacesgns.html", [
      [ "api", "namespacesgns_1_1api.html", [
        [ "author", "namespacesgns_1_1api_1_1author.html", [
          [ "request", "namespacesgns_1_1api_1_1author_1_1request.html", [
            [ "PendingExtrinsics", "classsgns_1_1api_1_1author_1_1request_1_1_pending_extrinsics.html", "classsgns_1_1api_1_1author_1_1request_1_1_pending_extrinsics" ],
            [ "SubmitExtrinsic", "classsgns_1_1api_1_1author_1_1request_1_1_submit_extrinsic.html", "classsgns_1_1api_1_1author_1_1request_1_1_submit_extrinsic" ]
          ] ],
          [ "AuthorJRpcProcessor", "classsgns_1_1api_1_1author_1_1_author_j_rpc_processor.html", "classsgns_1_1api_1_1author_1_1_author_j_rpc_processor" ]
        ] ],
        [ "chain", "namespacesgns_1_1api_1_1chain.html", [
          [ "request", "namespacesgns_1_1api_1_1chain_1_1request.html", [
            [ "GetBlockhash", "classsgns_1_1api_1_1chain_1_1request_1_1_get_blockhash.html", "classsgns_1_1api_1_1chain_1_1request_1_1_get_blockhash" ]
          ] ],
          [ "ChainJrpcProcessor", "classsgns_1_1api_1_1chain_1_1_chain_jrpc_processor.html", "classsgns_1_1api_1_1chain_1_1_chain_jrpc_processor" ]
        ] ],
        [ "state", "namespacesgns_1_1api_1_1state.html", [
          [ "request", "namespacesgns_1_1api_1_1state_1_1request.html", [
            [ "GetRuntimeVersion", "classsgns_1_1api_1_1state_1_1request_1_1_get_runtime_version.html", "classsgns_1_1api_1_1state_1_1request_1_1_get_runtime_version" ],
            [ "GetStorage", "classsgns_1_1api_1_1state_1_1request_1_1_get_storage.html", "classsgns_1_1api_1_1state_1_1request_1_1_get_storage" ],
            [ "SubscribeStorage", "classsgns_1_1api_1_1state_1_1request_1_1_subscribe_storage.html", "classsgns_1_1api_1_1state_1_1request_1_1_subscribe_storage" ],
            [ "UnsubscribeStorage", "classsgns_1_1api_1_1state_1_1request_1_1_unsubscribe_storage.html", "classsgns_1_1api_1_1state_1_1request_1_1_unsubscribe_storage" ]
          ] ],
          [ "StateJrpcProcessor", "classsgns_1_1api_1_1state_1_1_state_jrpc_processor.html", "classsgns_1_1api_1_1state_1_1_state_jrpc_processor" ]
        ] ],
        [ "system", "namespacesgns_1_1api_1_1system.html", [
          [ "request", "namespacesgns_1_1api_1_1system_1_1request.html", [
            [ "Chain", "classsgns_1_1api_1_1system_1_1request_1_1_chain.html", "classsgns_1_1api_1_1system_1_1request_1_1_chain" ],
            [ "Name", "classsgns_1_1api_1_1system_1_1request_1_1_name.html", "classsgns_1_1api_1_1system_1_1request_1_1_name" ],
            [ "Properties", "classsgns_1_1api_1_1system_1_1request_1_1_properties.html", "classsgns_1_1api_1_1system_1_1request_1_1_properties" ],
            [ "Version", "classsgns_1_1api_1_1system_1_1request_1_1_version.html", "classsgns_1_1api_1_1system_1_1request_1_1_version" ]
          ] ],
          [ "SystemJrpcProcessor", "classsgns_1_1api_1_1system_1_1_system_jrpc_processor.html", "classsgns_1_1api_1_1system_1_1_system_jrpc_processor" ]
        ] ],
        [ "ApiService", "classsgns_1_1api_1_1_api_service.html", "classsgns_1_1api_1_1_api_service" ],
        [ "AuthorApi", "classsgns_1_1api_1_1_author_api.html", "classsgns_1_1api_1_1_author_api" ],
        [ "AuthorApiImpl", "classsgns_1_1api_1_1_author_api_impl.html", "classsgns_1_1api_1_1_author_api_impl" ],
        [ "ChainApi", "classsgns_1_1api_1_1_chain_api.html", "classsgns_1_1api_1_1_chain_api" ],
        [ "ChainApiImpl", "classsgns_1_1api_1_1_chain_api_impl.html", "classsgns_1_1api_1_1_chain_api_impl" ],
        [ "HttpListenerImpl", "classsgns_1_1api_1_1_http_listener_impl.html", "classsgns_1_1api_1_1_http_listener_impl" ],
        [ "HttpSession", "classsgns_1_1api_1_1_http_session.html", "classsgns_1_1api_1_1_http_session" ],
        [ "JRpcProcessor", "classsgns_1_1api_1_1_j_rpc_processor.html", "classsgns_1_1api_1_1_j_rpc_processor" ],
        [ "JRpcServer", "classsgns_1_1api_1_1_j_rpc_server.html", "classsgns_1_1api_1_1_j_rpc_server" ],
        [ "JRpcServerImpl", "classsgns_1_1api_1_1_j_rpc_server_impl.html", "classsgns_1_1api_1_1_j_rpc_server_impl" ],
        [ "Listener", "classsgns_1_1api_1_1_listener.html", "classsgns_1_1api_1_1_listener" ],
        [ "Method", "classsgns_1_1api_1_1_method.html", "classsgns_1_1api_1_1_method" ],
        [ "RpcContext", "classsgns_1_1api_1_1_rpc_context.html", null ],
        [ "RpcThreadPool", "classsgns_1_1api_1_1_rpc_thread_pool.html", "classsgns_1_1api_1_1_rpc_thread_pool" ],
        [ "Session", "classsgns_1_1api_1_1_session.html", "classsgns_1_1api_1_1_session" ],
        [ "StateApi", "classsgns_1_1api_1_1_state_api.html", "classsgns_1_1api_1_1_state_api" ],
        [ "StateApiImpl", "classsgns_1_1api_1_1_state_api_impl.html", "classsgns_1_1api_1_1_state_api_impl" ],
        [ "SystemApi", "classsgns_1_1api_1_1_system_api.html", "classsgns_1_1api_1_1_system_api" ],
        [ "SystemApiImpl", "classsgns_1_1api_1_1_system_api_impl.html", "classsgns_1_1api_1_1_system_api_impl" ],
        [ "WsListenerImpl", "classsgns_1_1api_1_1_ws_listener_impl.html", "classsgns_1_1api_1_1_ws_listener_impl" ],
        [ "WsSession", "classsgns_1_1api_1_1_ws_session.html", "classsgns_1_1api_1_1_ws_session" ]
      ] ],
      [ "application", "namespacesgns_1_1application.html", [
        [ "AppConfiguration", "classsgns_1_1application_1_1_app_configuration.html", "classsgns_1_1application_1_1_app_configuration" ],
        [ "AppConfigurationImpl", "classsgns_1_1application_1_1_app_configuration_impl.html", "classsgns_1_1application_1_1_app_configuration_impl" ],
        [ "AppStateException", "structsgns_1_1application_1_1_app_state_exception.html", "structsgns_1_1application_1_1_app_state_exception" ],
        [ "AppStateManager", "classsgns_1_1application_1_1_app_state_manager.html", "classsgns_1_1application_1_1_app_state_manager" ],
        [ "AppStateManagerImpl", "classsgns_1_1application_1_1_app_state_manager_impl.html", "classsgns_1_1application_1_1_app_state_manager_impl" ],
        [ "BlockProducingNodeApplication", "classsgns_1_1application_1_1_block_producing_node_application.html", "classsgns_1_1application_1_1_block_producing_node_application" ],
        [ "ConfigurationStorage", "classsgns_1_1application_1_1_configuration_storage.html", "classsgns_1_1application_1_1_configuration_storage" ],
        [ "ConfigurationStorageImpl", "classsgns_1_1application_1_1_configuration_storage_impl.html", "classsgns_1_1application_1_1_configuration_storage_impl" ],
        [ "KeyStorage", "classsgns_1_1application_1_1_key_storage.html", "classsgns_1_1application_1_1_key_storage" ],
        [ "LocalKeyStorage", "classsgns_1_1application_1_1_local_key_storage.html", "classsgns_1_1application_1_1_local_key_storage" ],
        [ "SgnsApplication", "classsgns_1_1application_1_1_sgns_application.html", "classsgns_1_1application_1_1_sgns_application" ],
        [ "SyncingNodeApplication", "classsgns_1_1application_1_1_syncing_node_application.html", "classsgns_1_1application_1_1_syncing_node_application" ],
        [ "ValidatingNodeApplication", "classsgns_1_1application_1_1_validating_node_application.html", "classsgns_1_1application_1_1_validating_node_application" ]
      ] ],
      [ "authority", "namespacesgns_1_1authority.html", [
        [ "AuthorityManager", "classsgns_1_1authority_1_1_authority_manager.html", "classsgns_1_1authority_1_1_authority_manager" ],
        [ "AuthorityManagerImpl", "classsgns_1_1authority_1_1_authority_manager_impl.html", "classsgns_1_1authority_1_1_authority_manager_impl" ],
        [ "AuthorityUpdateObserver", "classsgns_1_1authority_1_1_authority_update_observer.html", "classsgns_1_1authority_1_1_authority_update_observer" ],
        [ "ScheduleNode", "classsgns_1_1authority_1_1_schedule_node.html", "classsgns_1_1authority_1_1_schedule_node" ]
      ] ],
      [ "authorship", "namespacesgns_1_1authorship.html", [
        [ "BlockBuilder", "classsgns_1_1authorship_1_1_block_builder.html", "classsgns_1_1authorship_1_1_block_builder" ],
        [ "BlockBuilderFactory", "classsgns_1_1authorship_1_1_block_builder_factory.html", "classsgns_1_1authorship_1_1_block_builder_factory" ],
        [ "BlockBuilderFactoryImpl", "classsgns_1_1authorship_1_1_block_builder_factory_impl.html", "classsgns_1_1authorship_1_1_block_builder_factory_impl" ],
        [ "BlockBuilderImpl", "classsgns_1_1authorship_1_1_block_builder_impl.html", "classsgns_1_1authorship_1_1_block_builder_impl" ],
        [ "Proposer", "classsgns_1_1authorship_1_1_proposer.html", "classsgns_1_1authorship_1_1_proposer" ],
        [ "ProposerImpl", "classsgns_1_1authorship_1_1_proposer_impl.html", "classsgns_1_1authorship_1_1_proposer_impl" ]
      ] ],
      [ "base", "namespacesgns_1_1base.html", [
        [ "Blob", "classsgns_1_1base_1_1_blob.html", "classsgns_1_1base_1_1_blob" ],
        [ "Buffer", "classsgns_1_1base_1_1_buffer.html", "classsgns_1_1base_1_1_buffer" ],
        [ "Wrapper", "structsgns_1_1base_1_1_wrapper.html", "structsgns_1_1base_1_1_wrapper" ]
      ] ],
      [ "blockchain", "namespacesgns_1_1blockchain.html", [
        [ "BlockHeaderRepository", "classsgns_1_1blockchain_1_1_block_header_repository.html", "classsgns_1_1blockchain_1_1_block_header_repository" ],
        [ "BlockStorage", "classsgns_1_1blockchain_1_1_block_storage.html", "classsgns_1_1blockchain_1_1_block_storage" ],
        [ "BlockTree", "structsgns_1_1blockchain_1_1_block_tree.html", "structsgns_1_1blockchain_1_1_block_tree" ],
        [ "BlockTreeImpl", "classsgns_1_1blockchain_1_1_block_tree_impl.html", "classsgns_1_1blockchain_1_1_block_tree_impl" ],
        [ "KeyValueBlockHeaderRepository", "classsgns_1_1blockchain_1_1_key_value_block_header_repository.html", "classsgns_1_1blockchain_1_1_key_value_block_header_repository" ],
        [ "KeyValueBlockStorage", "classsgns_1_1blockchain_1_1_key_value_block_storage.html", "classsgns_1_1blockchain_1_1_key_value_block_storage" ]
      ] ],
      [ "clock", "namespacesgns_1_1clock.html", [
        [ "BasicWaitableTimer", "classsgns_1_1clock_1_1_basic_waitable_timer.html", "classsgns_1_1clock_1_1_basic_waitable_timer" ],
        [ "Clock", "classsgns_1_1clock_1_1_clock.html", "classsgns_1_1clock_1_1_clock" ],
        [ "ClockImpl", "classsgns_1_1clock_1_1_clock_impl.html", "classsgns_1_1clock_1_1_clock_impl" ],
        [ "Timer", "structsgns_1_1clock_1_1_timer.html", "structsgns_1_1clock_1_1_timer" ]
      ] ],
      [ "crdt", "namespacesgns_1_1crdt.html", [
        [ "Broadcaster", "classsgns_1_1crdt_1_1_broadcaster.html", "classsgns_1_1crdt_1_1_broadcaster" ],
        [ "CrdtDatastore", "classsgns_1_1crdt_1_1_crdt_datastore.html", "classsgns_1_1crdt_1_1_crdt_datastore" ],
        [ "CrdtDataStoreTransaction", "classsgns_1_1crdt_1_1_crdt_data_store_transaction.html", "classsgns_1_1crdt_1_1_crdt_data_store_transaction" ],
        [ "CrdtHeads", "classsgns_1_1crdt_1_1_crdt_heads.html", "classsgns_1_1crdt_1_1_crdt_heads" ],
        [ "CrdtOptions", "structsgns_1_1crdt_1_1_crdt_options.html", "structsgns_1_1crdt_1_1_crdt_options" ],
        [ "CrdtSet", "classsgns_1_1crdt_1_1_crdt_set.html", "classsgns_1_1crdt_1_1_crdt_set" ],
        [ "DAGSyncer", "classsgns_1_1crdt_1_1_d_a_g_syncer.html", "classsgns_1_1crdt_1_1_d_a_g_syncer" ],
        [ "GlobalDB", "classsgns_1_1crdt_1_1_global_d_b.html", "classsgns_1_1crdt_1_1_global_d_b" ],
        [ "GraphsyncDAGSyncer", "classsgns_1_1crdt_1_1_graphsync_d_a_g_syncer.html", "classsgns_1_1crdt_1_1_graphsync_d_a_g_syncer" ],
        [ "HierarchicalKey", "classsgns_1_1crdt_1_1_hierarchical_key.html", "classsgns_1_1crdt_1_1_hierarchical_key" ],
        [ "KeyPairFileStorage", "classsgns_1_1crdt_1_1_key_pair_file_storage.html", "classsgns_1_1crdt_1_1_key_pair_file_storage" ],
        [ "PubSubBroadcaster", "classsgns_1_1crdt_1_1_pub_sub_broadcaster.html", "classsgns_1_1crdt_1_1_pub_sub_broadcaster" ],
        [ "PubSubBroadcasterExt", "classsgns_1_1crdt_1_1_pub_sub_broadcaster_ext.html", "classsgns_1_1crdt_1_1_pub_sub_broadcaster_ext" ],
        [ "SessionDAGSyncer", "classsgns_1_1crdt_1_1_session_d_a_g_syncer.html", "classsgns_1_1crdt_1_1_session_d_a_g_syncer" ]
      ] ],
      [ "crypto", "namespacesgns_1_1crypto.html", [
        [ "bip39", "namespacesgns_1_1crypto_1_1bip39.html", [
          [ "Dictionary", "classsgns_1_1crypto_1_1bip39_1_1_dictionary.html", "classsgns_1_1crypto_1_1bip39_1_1_dictionary" ],
          [ "EntropyAccumulator", "classsgns_1_1crypto_1_1bip39_1_1_entropy_accumulator.html", "classsgns_1_1crypto_1_1bip39_1_1_entropy_accumulator" ],
          [ "EntropyToken", "structsgns_1_1crypto_1_1bip39_1_1_entropy_token.html", "structsgns_1_1crypto_1_1bip39_1_1_entropy_token" ],
          [ "Mnemonic", "structsgns_1_1crypto_1_1bip39_1_1_mnemonic.html", "structsgns_1_1crypto_1_1bip39_1_1_mnemonic" ]
        ] ],
        [ "Bip39Provider", "classsgns_1_1crypto_1_1_bip39_provider.html", "classsgns_1_1crypto_1_1_bip39_provider" ],
        [ "Bip39ProviderImpl", "classsgns_1_1crypto_1_1_bip39_provider_impl.html", "classsgns_1_1crypto_1_1_bip39_provider_impl" ],
        [ "CryptoStore", "classsgns_1_1crypto_1_1_crypto_store.html", "classsgns_1_1crypto_1_1_crypto_store" ],
        [ "CryptoStoreImpl", "classsgns_1_1crypto_1_1_crypto_store_impl.html", "classsgns_1_1crypto_1_1_crypto_store_impl" ],
        [ "ED25519Keypair", "structsgns_1_1crypto_1_1_e_d25519_keypair.html", "structsgns_1_1crypto_1_1_e_d25519_keypair" ],
        [ "ED25519Provider", "classsgns_1_1crypto_1_1_e_d25519_provider.html", "classsgns_1_1crypto_1_1_e_d25519_provider" ],
        [ "ED25519ProviderImpl", "classsgns_1_1crypto_1_1_e_d25519_provider_impl.html", "classsgns_1_1crypto_1_1_e_d25519_provider_impl" ],
        [ "Hasher", "classsgns_1_1crypto_1_1_hasher.html", "classsgns_1_1crypto_1_1_hasher" ],
        [ "HasherImpl", "classsgns_1_1crypto_1_1_hasher_impl.html", "classsgns_1_1crypto_1_1_hasher_impl" ],
        [ "Pbkdf2Provider", "classsgns_1_1crypto_1_1_pbkdf2_provider.html", "classsgns_1_1crypto_1_1_pbkdf2_provider" ],
        [ "Pbkdf2ProviderImpl", "classsgns_1_1crypto_1_1_pbkdf2_provider_impl.html", "classsgns_1_1crypto_1_1_pbkdf2_provider_impl" ],
        [ "Secp256k1Provider", "classsgns_1_1crypto_1_1_secp256k1_provider.html", "classsgns_1_1crypto_1_1_secp256k1_provider" ],
        [ "Secp256k1ProviderImpl", "classsgns_1_1crypto_1_1_secp256k1_provider_impl.html", "classsgns_1_1crypto_1_1_secp256k1_provider_impl" ],
        [ "SR25519Keypair", "structsgns_1_1crypto_1_1_s_r25519_keypair.html", "structsgns_1_1crypto_1_1_s_r25519_keypair" ],
        [ "SR25519Provider", "classsgns_1_1crypto_1_1_s_r25519_provider.html", "classsgns_1_1crypto_1_1_s_r25519_provider" ],
        [ "SR25519ProviderImpl", "classsgns_1_1crypto_1_1_s_r25519_provider_impl.html", "classsgns_1_1crypto_1_1_s_r25519_provider_impl" ],
        [ "VRFOutput", "structsgns_1_1crypto_1_1_v_r_f_output.html", "structsgns_1_1crypto_1_1_v_r_f_output" ],
        [ "VRFProvider", "classsgns_1_1crypto_1_1_v_r_f_provider.html", "classsgns_1_1crypto_1_1_v_r_f_provider" ],
        [ "VRFProviderImpl", "classsgns_1_1crypto_1_1_v_r_f_provider_impl.html", "classsgns_1_1crypto_1_1_v_r_f_provider_impl" ],
        [ "VRFVerifyOutput", "structsgns_1_1crypto_1_1_v_r_f_verify_output.html", "structsgns_1_1crypto_1_1_v_r_f_verify_output" ]
      ] ],
      [ "extensions", "namespacesgns_1_1extensions.html", [
        [ "CryptoExtension", "classsgns_1_1extensions_1_1_crypto_extension.html", "classsgns_1_1extensions_1_1_crypto_extension" ],
        [ "Extension", "classsgns_1_1extensions_1_1_extension.html", "classsgns_1_1extensions_1_1_extension" ],
        [ "ExtensionFactory", "classsgns_1_1extensions_1_1_extension_factory.html", "classsgns_1_1extensions_1_1_extension_factory" ],
        [ "ExtensionFactoryImpl", "classsgns_1_1extensions_1_1_extension_factory_impl.html", "classsgns_1_1extensions_1_1_extension_factory_impl" ],
        [ "ExtensionImpl", "classsgns_1_1extensions_1_1_extension_impl.html", "classsgns_1_1extensions_1_1_extension_impl" ],
        [ "IOExtension", "classsgns_1_1extensions_1_1_i_o_extension.html", "classsgns_1_1extensions_1_1_i_o_extension" ],
        [ "MemoryExtension", "classsgns_1_1extensions_1_1_memory_extension.html", "classsgns_1_1extensions_1_1_memory_extension" ],
        [ "MiscExtension", "classsgns_1_1extensions_1_1_misc_extension.html", "classsgns_1_1extensions_1_1_misc_extension" ],
        [ "StorageExtension", "classsgns_1_1extensions_1_1_storage_extension.html", "classsgns_1_1extensions_1_1_storage_extension" ]
      ] ],
      [ "face", "namespacesgns_1_1face.html", [
        [ "ForwardIterator", "classsgns_1_1face_1_1_forward_iterator.html", "classsgns_1_1face_1_1_forward_iterator" ],
        [ "GenericIterator", "classsgns_1_1face_1_1_generic_iterator.html", "classsgns_1_1face_1_1_generic_iterator" ],
        [ "GenericList", "classsgns_1_1face_1_1_generic_list.html", "classsgns_1_1face_1_1_generic_list" ]
      ] ],
      [ "network", "namespacesgns_1_1network.html", [
        [ "BlockAnnounce", "structsgns_1_1network_1_1_block_announce.html", "structsgns_1_1network_1_1_block_announce" ],
        [ "BlockAttributes", "namespacesgns_1_1network.html#structsgns_1_1network_1_1_block_attributes", "namespacesgns_1_1network_structsgns_1_1network_1_1_block_attributes_dup" ],
        [ "BlocksRequest", "structsgns_1_1network_1_1_blocks_request.html", "structsgns_1_1network_1_1_blocks_request" ],
        [ "BlocksResponse", "namespacesgns_1_1network.html#structsgns_1_1network_1_1_blocks_response", "namespacesgns_1_1network_structsgns_1_1network_1_1_blocks_response_dup" ],
        [ "DummySyncProtocolClient", "classsgns_1_1network_1_1_dummy_sync_protocol_client.html", "classsgns_1_1network_1_1_dummy_sync_protocol_client" ],
        [ "ExtrinsicGossiper", "structsgns_1_1network_1_1_extrinsic_gossiper.html", "structsgns_1_1network_1_1_extrinsic_gossiper" ],
        [ "ExtrinsicObserver", "classsgns_1_1network_1_1_extrinsic_observer.html", "classsgns_1_1network_1_1_extrinsic_observer" ],
        [ "ExtrinsicObserverImpl", "classsgns_1_1network_1_1_extrinsic_observer_impl.html", "classsgns_1_1network_1_1_extrinsic_observer_impl" ],
        [ "Gossiper", "structsgns_1_1network_1_1_gossiper.html", "structsgns_1_1network_1_1_gossiper" ],
        [ "GossiperBroadcast", "classsgns_1_1network_1_1_gossiper_broadcast.html", "classsgns_1_1network_1_1_gossiper_broadcast" ],
        [ "GossipMessage", "structsgns_1_1network_1_1_gossip_message.html", "structsgns_1_1network_1_1_gossip_message" ],
        [ "LoopbackStream", "classsgns_1_1network_1_1_loopback_stream.html", "classsgns_1_1network_1_1_loopback_stream" ],
        [ "MessageReadWriter", "structsgns_1_1network_1_1_message_read_writer.html", "structsgns_1_1network_1_1_message_read_writer" ],
        [ "MessageReadWriter< Adapter, NoSink >", "structsgns_1_1network_1_1_message_read_writer_3_01_adapter_00_01_no_sink_01_4.html", "structsgns_1_1network_1_1_message_read_writer_3_01_adapter_00_01_no_sink_01_4" ],
        [ "NoSink", "namespacesgns_1_1network.html#structsgns_1_1network_1_1_no_sink", null ],
        [ "OwnPeerInfo", "structsgns_1_1network_1_1_own_peer_info.html", "structsgns_1_1network_1_1_own_peer_info" ],
        [ "PeerList", "structsgns_1_1network_1_1_peer_list.html", "structsgns_1_1network_1_1_peer_list" ],
        [ "ProductionObserver", "structsgns_1_1network_1_1_production_observer.html", "structsgns_1_1network_1_1_production_observer" ],
        [ "ProtobufMessageReadWriter", "classsgns_1_1network_1_1_protobuf_message_read_writer.html", "classsgns_1_1network_1_1_protobuf_message_read_writer" ],
        [ "RemoteSyncProtocolClient", "classsgns_1_1network_1_1_remote_sync_protocol_client.html", "classsgns_1_1network_1_1_remote_sync_protocol_client" ],
        [ "Router", "classsgns_1_1network_1_1_router.html", "classsgns_1_1network_1_1_router" ],
        [ "RouterLibp2p", "classsgns_1_1network_1_1_router_libp2p.html", "classsgns_1_1network_1_1_router_libp2p" ],
        [ "RPC", "structsgns_1_1network_1_1_r_p_c.html", "structsgns_1_1network_1_1_r_p_c" ],
        [ "ScaleMessageReadWriter", "classsgns_1_1network_1_1_scale_message_read_writer.html", "classsgns_1_1network_1_1_scale_message_read_writer" ],
        [ "SyncClientsSet", "namespacesgns_1_1network.html#structsgns_1_1network_1_1_sync_clients_set", "namespacesgns_1_1network_structsgns_1_1network_1_1_sync_clients_set_dup" ],
        [ "SyncProtocolClient", "structsgns_1_1network_1_1_sync_protocol_client.html", "structsgns_1_1network_1_1_sync_protocol_client" ],
        [ "SyncProtocolObserver", "structsgns_1_1network_1_1_sync_protocol_observer.html", "structsgns_1_1network_1_1_sync_protocol_observer" ],
        [ "SyncProtocolObserverImpl", "classsgns_1_1network_1_1_sync_protocol_observer_impl.html", "classsgns_1_1network_1_1_sync_protocol_observer_impl" ],
        [ "TransactionAnnounce", "namespacesgns_1_1network.html#structsgns_1_1network_1_1_transaction_announce", "namespacesgns_1_1network_structsgns_1_1network_1_1_transaction_announce_dup" ]
      ] ],
      [ "primitives", "namespacesgns_1_1primitives.html", [
        [ "detail", "namespacesgns_1_1primitives_1_1detail.html", [
          [ "BlockInfoT", "structsgns_1_1primitives_1_1detail_1_1_block_info_t.html", "structsgns_1_1primitives_1_1detail_1_1_block_info_t" ],
          [ "DigestItemCommon", "structsgns_1_1primitives_1_1detail_1_1_digest_item_common.html", "structsgns_1_1primitives_1_1detail_1_1_digest_item_common" ]
        ] ],
        [ "parachain", "namespacesgns_1_1primitives_1_1parachain.html", [
          [ "Relay", "namespacesgns_1_1primitives_1_1parachain.html#structsgns_1_1primitives_1_1parachain_1_1_relay", null ]
        ] ],
        [ "Authority", "structsgns_1_1primitives_1_1_authority.html", "structsgns_1_1primitives_1_1_authority" ],
        [ "AuthorityId", "structsgns_1_1primitives_1_1_authority_id.html", "structsgns_1_1primitives_1_1_authority_id" ],
        [ "AuthorityList", "structsgns_1_1primitives_1_1_authority_list.html", null ],
        [ "AuthorityListChange", "structsgns_1_1primitives_1_1_authority_list_change.html", "structsgns_1_1primitives_1_1_authority_list_change" ],
        [ "Block", "structsgns_1_1primitives_1_1_block.html", "structsgns_1_1primitives_1_1_block" ],
        [ "BlockData", "structsgns_1_1primitives_1_1_block_data.html", "structsgns_1_1primitives_1_1_block_data" ],
        [ "BlockHeader", "structsgns_1_1primitives_1_1_block_header.html", "structsgns_1_1primitives_1_1_block_header" ],
        [ "CheckInherentsResult", "namespacesgns_1_1primitives.html#structsgns_1_1primitives_1_1_check_inherents_result", "namespacesgns_1_1primitives_structsgns_1_1primitives_1_1_check_inherents_result_dup" ],
        [ "DelayInChain", "structsgns_1_1primitives_1_1_delay_in_chain.html", "structsgns_1_1primitives_1_1_delay_in_chain" ],
        [ "Extrinsic", "structsgns_1_1primitives_1_1_extrinsic.html", "structsgns_1_1primitives_1_1_extrinsic" ],
        [ "ForcedChange", "structsgns_1_1primitives_1_1_forced_change.html", "structsgns_1_1primitives_1_1_forced_change" ],
        [ "InherentData", "structsgns_1_1primitives_1_1_inherent_data.html", "structsgns_1_1primitives_1_1_inherent_data" ],
        [ "Justification", "structsgns_1_1primitives_1_1_justification.html", "structsgns_1_1primitives_1_1_justification" ],
        [ "OnDisabled", "namespacesgns_1_1primitives.html#structsgns_1_1primitives_1_1_on_disabled", "namespacesgns_1_1primitives_structsgns_1_1primitives_1_1_on_disabled_dup" ],
        [ "Pause", "structsgns_1_1primitives_1_1_pause.html", "structsgns_1_1primitives_1_1_pause" ],
        [ "PreRuntime", "structsgns_1_1primitives_1_1_pre_runtime.html", null ],
        [ "ProductionConfiguration", "namespacesgns_1_1primitives.html#structsgns_1_1primitives_1_1_production_configuration", "namespacesgns_1_1primitives_structsgns_1_1primitives_1_1_production_configuration_dup" ],
        [ "Resume", "structsgns_1_1primitives_1_1_resume.html", "structsgns_1_1primitives_1_1_resume" ],
        [ "ScheduledChange", "structsgns_1_1primitives_1_1_scheduled_change.html", "structsgns_1_1primitives_1_1_scheduled_change" ],
        [ "Seal", "structsgns_1_1primitives_1_1_seal.html", null ],
        [ "Session", "namespacesgns_1_1primitives.html#structsgns_1_1primitives_1_1_session", "namespacesgns_1_1primitives_structsgns_1_1primitives_1_1_session_dup" ],
        [ "Subscriber", "namespacesgns_1_1primitives.html#structsgns_1_1primitives_1_1_subscriber", "namespacesgns_1_1primitives_structsgns_1_1primitives_1_1_subscriber_dup" ],
        [ "Transaction", "structsgns_1_1primitives_1_1_transaction.html", "structsgns_1_1primitives_1_1_transaction" ],
        [ "ValidTransaction", "structsgns_1_1primitives_1_1_valid_transaction.html", "structsgns_1_1primitives_1_1_valid_transaction" ],
        [ "Verification", "structsgns_1_1primitives_1_1_verification.html", "structsgns_1_1primitives_1_1_verification" ],
        [ "Version", "structsgns_1_1primitives_1_1_version.html", "structsgns_1_1primitives_1_1_version" ]
      ] ],
      [ "processing", "namespacesgns_1_1processing.html", [
        [ "ProcessingCore", "classsgns_1_1processing_1_1_processing_core.html", "classsgns_1_1processing_1_1_processing_core" ],
        [ "ProcessingEngine", "classsgns_1_1processing_1_1_processing_engine.html", "classsgns_1_1processing_1_1_processing_engine" ],
        [ "ProcessingNode", "classsgns_1_1processing_1_1_processing_node.html", "classsgns_1_1processing_1_1_processing_node" ],
        [ "ProcessingServiceImpl", "classsgns_1_1processing_1_1_processing_service_impl.html", "classsgns_1_1processing_1_1_processing_service_impl" ],
        [ "ProcessingSubTaskQueue", "classsgns_1_1processing_1_1_processing_sub_task_queue.html", "classsgns_1_1processing_1_1_processing_sub_task_queue" ],
        [ "ProcessingSubTaskQueueChannel", "classsgns_1_1processing_1_1_processing_sub_task_queue_channel.html", "classsgns_1_1processing_1_1_processing_sub_task_queue_channel" ],
        [ "ProcessingSubTaskQueueChannelPubSub", "classsgns_1_1processing_1_1_processing_sub_task_queue_channel_pub_sub.html", "classsgns_1_1processing_1_1_processing_sub_task_queue_channel_pub_sub" ],
        [ "ProcessingSubTaskQueueManager", "classsgns_1_1processing_1_1_processing_sub_task_queue_manager.html", "classsgns_1_1processing_1_1_processing_sub_task_queue_manager" ],
        [ "ProcessingValidationCore", "classsgns_1_1processing_1_1_processing_validation_core.html", "classsgns_1_1processing_1_1_processing_validation_core" ],
        [ "SubTaskEnqueuer", "classsgns_1_1processing_1_1_sub_task_enqueuer.html", "classsgns_1_1processing_1_1_sub_task_enqueuer" ],
        [ "SubTaskEnqueuerImpl", "classsgns_1_1processing_1_1_sub_task_enqueuer_impl.html", "classsgns_1_1processing_1_1_sub_task_enqueuer_impl" ],
        [ "SubTaskQueueAccessor", "classsgns_1_1processing_1_1_sub_task_queue_accessor.html", "classsgns_1_1processing_1_1_sub_task_queue_accessor" ],
        [ "SubTaskQueueAccessorImpl", "classsgns_1_1processing_1_1_sub_task_queue_accessor_impl.html", "classsgns_1_1processing_1_1_sub_task_queue_accessor_impl" ],
        [ "SubTaskResultStorage", "classsgns_1_1processing_1_1_sub_task_result_storage.html", "classsgns_1_1processing_1_1_sub_task_result_storage" ],
        [ "SubTaskStateStorage", "classsgns_1_1processing_1_1_sub_task_state_storage.html", "classsgns_1_1processing_1_1_sub_task_state_storage" ]
      ] ],
      [ "runtime", "namespacesgns_1_1runtime.html", [
        [ "binaryen", "namespacesgns_1_1runtime_1_1binaryen.html", [
          [ "BlockBuilderImpl", "classsgns_1_1runtime_1_1binaryen_1_1_block_builder_impl.html", "classsgns_1_1runtime_1_1binaryen_1_1_block_builder_impl" ],
          [ "CoreFactoryImpl", "classsgns_1_1runtime_1_1binaryen_1_1_core_factory_impl.html", "classsgns_1_1runtime_1_1binaryen_1_1_core_factory_impl" ],
          [ "CoreImpl", "classsgns_1_1runtime_1_1binaryen_1_1_core_impl.html", "classsgns_1_1runtime_1_1binaryen_1_1_core_impl" ],
          [ "FinalityApiImpl", "classsgns_1_1runtime_1_1binaryen_1_1_finality_api_impl.html", "classsgns_1_1runtime_1_1binaryen_1_1_finality_api_impl" ],
          [ "MetadataImpl", "classsgns_1_1runtime_1_1binaryen_1_1_metadata_impl.html", "classsgns_1_1runtime_1_1binaryen_1_1_metadata_impl" ],
          [ "OffchainWorkerImpl", "classsgns_1_1runtime_1_1binaryen_1_1_offchain_worker_impl.html", "classsgns_1_1runtime_1_1binaryen_1_1_offchain_worker_impl" ],
          [ "ParachainHostImpl", "classsgns_1_1runtime_1_1binaryen_1_1_parachain_host_impl.html", "classsgns_1_1runtime_1_1binaryen_1_1_parachain_host_impl" ],
          [ "ProductionApiImpl", "classsgns_1_1runtime_1_1binaryen_1_1_production_api_impl.html", "classsgns_1_1runtime_1_1binaryen_1_1_production_api_impl" ],
          [ "RuntimeApi", "classsgns_1_1runtime_1_1binaryen_1_1_runtime_api.html", "classsgns_1_1runtime_1_1binaryen_1_1_runtime_api" ],
          [ "RuntimeEnvironment", "classsgns_1_1runtime_1_1binaryen_1_1_runtime_environment.html", "classsgns_1_1runtime_1_1binaryen_1_1_runtime_environment" ],
          [ "RuntimeExternalInterface", "classsgns_1_1runtime_1_1binaryen_1_1_runtime_external_interface.html", "classsgns_1_1runtime_1_1binaryen_1_1_runtime_external_interface" ],
          [ "RuntimeManager", "classsgns_1_1runtime_1_1binaryen_1_1_runtime_manager.html", "classsgns_1_1runtime_1_1binaryen_1_1_runtime_manager" ],
          [ "TaggedTransactionQueueImpl", "classsgns_1_1runtime_1_1binaryen_1_1_tagged_transaction_queue_impl.html", "classsgns_1_1runtime_1_1binaryen_1_1_tagged_transaction_queue_impl" ],
          [ "WasmExecutor", "classsgns_1_1runtime_1_1binaryen_1_1_wasm_executor.html", "classsgns_1_1runtime_1_1binaryen_1_1_wasm_executor" ],
          [ "WasmMemoryImpl", "classsgns_1_1runtime_1_1binaryen_1_1_wasm_memory_impl.html", "classsgns_1_1runtime_1_1binaryen_1_1_wasm_memory_impl" ],
          [ "WasmModule", "classsgns_1_1runtime_1_1binaryen_1_1_wasm_module.html", "classsgns_1_1runtime_1_1binaryen_1_1_wasm_module" ],
          [ "WasmModuleFactory", "classsgns_1_1runtime_1_1binaryen_1_1_wasm_module_factory.html", "classsgns_1_1runtime_1_1binaryen_1_1_wasm_module_factory" ],
          [ "WasmModuleFactoryImpl", "classsgns_1_1runtime_1_1binaryen_1_1_wasm_module_factory_impl.html", "classsgns_1_1runtime_1_1binaryen_1_1_wasm_module_factory_impl" ],
          [ "WasmModuleImpl", "classsgns_1_1runtime_1_1binaryen_1_1_wasm_module_impl.html", "classsgns_1_1runtime_1_1binaryen_1_1_wasm_module_impl" ],
          [ "WasmModuleInstance", "classsgns_1_1runtime_1_1binaryen_1_1_wasm_module_instance.html", "classsgns_1_1runtime_1_1binaryen_1_1_wasm_module_instance" ],
          [ "WasmModuleInstanceImpl", "classsgns_1_1runtime_1_1binaryen_1_1_wasm_module_instance_impl.html", "classsgns_1_1runtime_1_1binaryen_1_1_wasm_module_instance_impl" ]
        ] ],
        [ "dummy", "namespacesgns_1_1runtime_1_1dummy.html", [
          [ "FinalityApiDummy", "classsgns_1_1runtime_1_1dummy_1_1_finality_api_dummy.html", "classsgns_1_1runtime_1_1dummy_1_1_finality_api_dummy" ]
        ] ],
        [ "BlockBuilder", "classsgns_1_1runtime_1_1_block_builder.html", "classsgns_1_1runtime_1_1_block_builder" ],
        [ "ConstWasmProvider", "classsgns_1_1runtime_1_1_const_wasm_provider.html", "classsgns_1_1runtime_1_1_const_wasm_provider" ],
        [ "Core", "classsgns_1_1runtime_1_1_core.html", "classsgns_1_1runtime_1_1_core" ],
        [ "CoreFactory", "classsgns_1_1runtime_1_1_core_factory.html", "classsgns_1_1runtime_1_1_core_factory" ],
        [ "FinalityApi", "classsgns_1_1runtime_1_1_finality_api.html", "classsgns_1_1runtime_1_1_finality_api" ],
        [ "Metadata", "classsgns_1_1runtime_1_1_metadata.html", "classsgns_1_1runtime_1_1_metadata" ],
        [ "OffchainWorker", "classsgns_1_1runtime_1_1_offchain_worker.html", "classsgns_1_1runtime_1_1_offchain_worker" ],
        [ "ParachainHost", "classsgns_1_1runtime_1_1_parachain_host.html", "classsgns_1_1runtime_1_1_parachain_host" ],
        [ "ProductionApi", "classsgns_1_1runtime_1_1_production_api.html", "classsgns_1_1runtime_1_1_production_api" ],
        [ "StorageWasmProvider", "classsgns_1_1runtime_1_1_storage_wasm_provider.html", "classsgns_1_1runtime_1_1_storage_wasm_provider" ],
        [ "TaggedTransactionQueue", "classsgns_1_1runtime_1_1_tagged_transaction_queue.html", "classsgns_1_1runtime_1_1_tagged_transaction_queue" ],
        [ "TrieStorageProvider", "classsgns_1_1runtime_1_1_trie_storage_provider.html", "classsgns_1_1runtime_1_1_trie_storage_provider" ],
        [ "TrieStorageProviderImpl", "classsgns_1_1runtime_1_1_trie_storage_provider_impl.html", "classsgns_1_1runtime_1_1_trie_storage_provider_impl" ],
        [ "WasmMemory", "classsgns_1_1runtime_1_1_wasm_memory.html", "classsgns_1_1runtime_1_1_wasm_memory" ],
        [ "WasmProvider", "classsgns_1_1runtime_1_1_wasm_provider.html", "classsgns_1_1runtime_1_1_wasm_provider" ],
        [ "WasmResult", "structsgns_1_1runtime_1_1_wasm_result.html", "structsgns_1_1runtime_1_1_wasm_result" ]
      ] ],
      [ "scale", "namespacesgns_1_1scale.html", [
        [ "compact", "namespacesgns_1_1scale_1_1compact.html", [
          [ "EncodingCategoryLimits", "structsgns_1_1scale_1_1compact_1_1_encoding_category_limits.html", "structsgns_1_1scale_1_1compact_1_1_encoding_category_limits" ]
        ] ],
        [ "detail", "namespacesgns_1_1scale_1_1detail.html", [
          [ "tuple_impl", "namespacesgns_1_1scale_1_1detail_1_1tuple__impl.html", [
            [ "TupleDecoder", "classsgns_1_1scale_1_1detail_1_1tuple__impl_1_1_tuple_decoder.html", "classsgns_1_1scale_1_1detail_1_1tuple__impl_1_1_tuple_decoder" ],
            [ "TupleEncoder", "classsgns_1_1scale_1_1detail_1_1tuple__impl_1_1_tuple_encoder.html", "classsgns_1_1scale_1_1detail_1_1tuple__impl_1_1_tuple_encoder" ]
          ] ],
          [ "variant_impl", "namespacesgns_1_1scale_1_1detail_1_1variant__impl.html", [
            [ "VariantDecoder", "classsgns_1_1scale_1_1detail_1_1variant__impl_1_1_variant_decoder.html", "classsgns_1_1scale_1_1detail_1_1variant__impl_1_1_variant_decoder" ],
            [ "VariantEncoder", "classsgns_1_1scale_1_1detail_1_1variant__impl_1_1_variant_encoder.html", "classsgns_1_1scale_1_1detail_1_1variant__impl_1_1_variant_encoder" ]
          ] ]
        ] ],
        [ "ScaleDecoderStream", "classsgns_1_1scale_1_1_scale_decoder_stream.html", "classsgns_1_1scale_1_1_scale_decoder_stream" ],
        [ "ScaleEncoderStream", "classsgns_1_1scale_1_1_scale_encoder_stream.html", "classsgns_1_1scale_1_1_scale_encoder_stream" ]
      ] ],
      [ "storage", "namespacesgns_1_1storage.html", [
        [ "changes_trie", "namespacesgns_1_1storage_1_1changes__trie.html", [
          [ "ChangesTracker", "classsgns_1_1storage_1_1changes__trie_1_1_changes_tracker.html", "classsgns_1_1storage_1_1changes__trie_1_1_changes_tracker" ],
          [ "ChangesTrie", "classsgns_1_1storage_1_1changes__trie_1_1_changes_trie.html", "classsgns_1_1storage_1_1changes__trie_1_1_changes_trie" ],
          [ "ChangesTrieConfig", "namespacesgns_1_1storage_1_1changes__trie.html#structsgns_1_1storage_1_1changes__trie_1_1_changes_trie_config", "namespacesgns_1_1storage_1_1changes__trie_structsgns_1_1storage_1_1changes__trie_1_1_changes_trie_config_dup" ],
          [ "StorageChangesTrackerImpl", "classsgns_1_1storage_1_1changes__trie_1_1_storage_changes_tracker_impl.html", "classsgns_1_1storage_1_1changes__trie_1_1_storage_changes_tracker_impl" ]
        ] ],
        [ "face", "namespacesgns_1_1storage_1_1face.html", [
          [ "Batchable", "structsgns_1_1storage_1_1face_1_1_batchable.html", "structsgns_1_1storage_1_1face_1_1_batchable" ],
          [ "BatchWriteMap", "structsgns_1_1storage_1_1face_1_1_batch_write_map.html", null ],
          [ "GenericMap", "structsgns_1_1storage_1_1face_1_1_generic_map.html", null ],
          [ "GenericStorage", "structsgns_1_1storage_1_1face_1_1_generic_storage.html", null ],
          [ "Iterable", "structsgns_1_1storage_1_1face_1_1_iterable.html", "structsgns_1_1storage_1_1face_1_1_iterable" ],
          [ "MapCursor", "structsgns_1_1storage_1_1face_1_1_map_cursor.html", "structsgns_1_1storage_1_1face_1_1_map_cursor" ],
          [ "Readable", "structsgns_1_1storage_1_1face_1_1_readable.html", "structsgns_1_1storage_1_1face_1_1_readable" ],
          [ "ReadOnlyMap", "structsgns_1_1storage_1_1face_1_1_read_only_map.html", null ],
          [ "Writeable", "structsgns_1_1storage_1_1face_1_1_writeable.html", "structsgns_1_1storage_1_1face_1_1_writeable" ],
          [ "WriteBatch", "structsgns_1_1storage_1_1face_1_1_write_batch.html", "structsgns_1_1storage_1_1face_1_1_write_batch" ]
        ] ],
        [ "trie", "namespacesgns_1_1storage_1_1trie.html", [
          [ "BranchNode", "structsgns_1_1storage_1_1trie_1_1_branch_node.html", "structsgns_1_1storage_1_1trie_1_1_branch_node" ],
          [ "BufferStream", "classsgns_1_1storage_1_1trie_1_1_buffer_stream.html", "classsgns_1_1storage_1_1trie_1_1_buffer_stream" ],
          [ "Codec", "classsgns_1_1storage_1_1trie_1_1_codec.html", "classsgns_1_1storage_1_1trie_1_1_codec" ],
          [ "DummyNode", "structsgns_1_1storage_1_1trie_1_1_dummy_node.html", "structsgns_1_1storage_1_1trie_1_1_dummy_node" ],
          [ "EphemeralTrieBatch", "classsgns_1_1storage_1_1trie_1_1_ephemeral_trie_batch.html", null ],
          [ "EphemeralTrieBatchImpl", "classsgns_1_1storage_1_1trie_1_1_ephemeral_trie_batch_impl.html", "classsgns_1_1storage_1_1trie_1_1_ephemeral_trie_batch_impl" ],
          [ "KeyNibbles", "structsgns_1_1storage_1_1trie_1_1_key_nibbles.html", "structsgns_1_1storage_1_1trie_1_1_key_nibbles" ],
          [ "LeafNode", "structsgns_1_1storage_1_1trie_1_1_leaf_node.html", "structsgns_1_1storage_1_1trie_1_1_leaf_node" ],
          [ "Node", "structsgns_1_1storage_1_1trie_1_1_node.html", "structsgns_1_1storage_1_1trie_1_1_node" ],
          [ "PersistentTrieBatch", "classsgns_1_1storage_1_1trie_1_1_persistent_trie_batch.html", "classsgns_1_1storage_1_1trie_1_1_persistent_trie_batch" ],
          [ "PersistentTrieBatchImpl", "classsgns_1_1storage_1_1trie_1_1_persistent_trie_batch_impl.html", "classsgns_1_1storage_1_1trie_1_1_persistent_trie_batch_impl" ],
          [ "SuperGeniusCodec", "classsgns_1_1storage_1_1trie_1_1_super_genius_codec.html", "classsgns_1_1storage_1_1trie_1_1_super_genius_codec" ],
          [ "SuperGeniusNode", "structsgns_1_1storage_1_1trie_1_1_super_genius_node.html", "structsgns_1_1storage_1_1trie_1_1_super_genius_node" ],
          [ "SuperGeniusTrie", "classsgns_1_1storage_1_1trie_1_1_super_genius_trie.html", "classsgns_1_1storage_1_1trie_1_1_super_genius_trie" ],
          [ "SuperGeniusTrieCursor", "classsgns_1_1storage_1_1trie_1_1_super_genius_trie_cursor.html", "classsgns_1_1storage_1_1trie_1_1_super_genius_trie_cursor" ],
          [ "SuperGeniusTrieFactory", "classsgns_1_1storage_1_1trie_1_1_super_genius_trie_factory.html", "classsgns_1_1storage_1_1trie_1_1_super_genius_trie_factory" ],
          [ "SuperGeniusTrieFactoryImpl", "classsgns_1_1storage_1_1trie_1_1_super_genius_trie_factory_impl.html", "classsgns_1_1storage_1_1trie_1_1_super_genius_trie_factory_impl" ],
          [ "SuperGeniusTrieImpl", "classsgns_1_1storage_1_1trie_1_1_super_genius_trie_impl.html", "classsgns_1_1storage_1_1trie_1_1_super_genius_trie_impl" ],
          [ "TopperTrieBatch", "classsgns_1_1storage_1_1trie_1_1_topper_trie_batch.html", "classsgns_1_1storage_1_1trie_1_1_topper_trie_batch" ],
          [ "TopperTrieBatchImpl", "classsgns_1_1storage_1_1trie_1_1_topper_trie_batch_impl.html", "classsgns_1_1storage_1_1trie_1_1_topper_trie_batch_impl" ],
          [ "TrieBatch", "classsgns_1_1storage_1_1trie_1_1_trie_batch.html", "classsgns_1_1storage_1_1trie_1_1_trie_batch" ],
          [ "TrieSerializer", "classsgns_1_1storage_1_1trie_1_1_trie_serializer.html", "classsgns_1_1storage_1_1trie_1_1_trie_serializer" ],
          [ "TrieSerializerImpl", "classsgns_1_1storage_1_1trie_1_1_trie_serializer_impl.html", "classsgns_1_1storage_1_1trie_1_1_trie_serializer_impl" ],
          [ "TrieStorage", "classsgns_1_1storage_1_1trie_1_1_trie_storage.html", "classsgns_1_1storage_1_1trie_1_1_trie_storage" ],
          [ "TrieStorageBackend", "classsgns_1_1storage_1_1trie_1_1_trie_storage_backend.html", "classsgns_1_1storage_1_1trie_1_1_trie_storage_backend" ],
          [ "TrieStorageBackendBatch", "classsgns_1_1storage_1_1trie_1_1_trie_storage_backend_batch.html", "classsgns_1_1storage_1_1trie_1_1_trie_storage_backend_batch" ],
          [ "TrieStorageBackendImpl", "classsgns_1_1storage_1_1trie_1_1_trie_storage_backend_impl.html", "classsgns_1_1storage_1_1trie_1_1_trie_storage_backend_impl" ],
          [ "TrieStorageImpl", "classsgns_1_1storage_1_1trie_1_1_trie_storage_impl.html", "classsgns_1_1storage_1_1trie_1_1_trie_storage_impl" ]
        ] ],
        [ "InMemoryBatch", "classsgns_1_1storage_1_1_in_memory_batch.html", "classsgns_1_1storage_1_1_in_memory_batch" ],
        [ "InMemoryStorage", "classsgns_1_1storage_1_1_in_memory_storage.html", "classsgns_1_1storage_1_1_in_memory_storage" ],
        [ "rocksdb", "classsgns_1_1storage_1_1rocksdb.html", "classsgns_1_1storage_1_1rocksdb" ]
      ] ],
      [ "subscription", "namespacesgns_1_1subscription.html", [
        [ "Subscriber", "classsgns_1_1subscription_1_1_subscriber.html", "classsgns_1_1subscription_1_1_subscriber" ],
        [ "SubscriptionEngine", "classsgns_1_1subscription_1_1_subscription_engine.html", "classsgns_1_1subscription_1_1_subscription_engine" ]
      ] ],
      [ "transaction_pool", "namespacesgns_1_1transaction__pool.html", [
        [ "PoolModerator", "classsgns_1_1transaction__pool_1_1_pool_moderator.html", "classsgns_1_1transaction__pool_1_1_pool_moderator" ],
        [ "PoolModeratorImpl", "classsgns_1_1transaction__pool_1_1_pool_moderator_impl.html", "classsgns_1_1transaction__pool_1_1_pool_moderator_impl" ],
        [ "TransactionPool", "classsgns_1_1transaction__pool_1_1_transaction_pool.html", "classsgns_1_1transaction__pool_1_1_transaction_pool" ],
        [ "TransactionPoolImpl", "classsgns_1_1transaction__pool_1_1_transaction_pool_impl.html", "classsgns_1_1transaction__pool_1_1_transaction_pool_impl" ]
      ] ],
      [ "verification", "namespacesgns_1_1verification.html", [
        [ "finality", "namespacesgns_1_1verification_1_1finality.html", [
          [ "detail", "namespacesgns_1_1verification_1_1finality_1_1detail.html", [
            [ "Equivocation", "namespacesgns_1_1verification_1_1finality_1_1detail.html#structsgns_1_1verification_1_1finality_1_1detail_1_1_equivocation", "namespacesgns_1_1verification_1_1finality_1_1detail_structsgns_1_1verification_1_1finality_1_1detail_1_1_equivocation_dup" ]
          ] ],
          [ "Chain", "structsgns_1_1verification_1_1finality_1_1_chain.html", "structsgns_1_1verification_1_1finality_1_1_chain" ],
          [ "Commit", "namespacesgns_1_1verification_1_1finality.html#structsgns_1_1verification_1_1finality_1_1_commit", "namespacesgns_1_1verification_1_1finality_structsgns_1_1verification_1_1finality_1_1_commit_dup" ],
          [ "CompletedRound", "structsgns_1_1verification_1_1finality_1_1_completed_round.html", "structsgns_1_1verification_1_1finality_1_1_completed_round" ],
          [ "Environment", "structsgns_1_1verification_1_1finality_1_1_environment.html", "structsgns_1_1verification_1_1finality_1_1_environment" ],
          [ "EnvironmentImpl", "classsgns_1_1verification_1_1finality_1_1_environment_impl.html", "classsgns_1_1verification_1_1finality_1_1_environment_impl" ],
          [ "Equivocated", "namespacesgns_1_1verification_1_1finality.html#structsgns_1_1verification_1_1finality_1_1_equivocated", "namespacesgns_1_1verification_1_1finality_structsgns_1_1verification_1_1finality_1_1_equivocated_dup" ],
          [ "Fin", "namespacesgns_1_1verification_1_1finality.html#structsgns_1_1verification_1_1finality_1_1_fin", "namespacesgns_1_1verification_1_1finality_structsgns_1_1verification_1_1finality_1_1_fin_dup" ],
          [ "Finality", "classsgns_1_1verification_1_1finality_1_1_finality.html", "classsgns_1_1verification_1_1finality_1_1_finality" ],
          [ "FinalityConfig", "namespacesgns_1_1verification_1_1finality.html#structsgns_1_1verification_1_1finality_1_1_finality_config", "namespacesgns_1_1verification_1_1finality_structsgns_1_1verification_1_1finality_1_1_finality_config_dup" ],
          [ "FinalityImpl", "classsgns_1_1verification_1_1finality_1_1_finality_impl.html", "classsgns_1_1verification_1_1finality_1_1_finality_impl" ],
          [ "FinalityJustification", "namespacesgns_1_1verification_1_1finality.html#structsgns_1_1verification_1_1finality_1_1_finality_justification", "namespacesgns_1_1verification_1_1finality_structsgns_1_1verification_1_1finality_1_1_finality_justification_dup" ],
          [ "FinalizationComposite", "classsgns_1_1verification_1_1finality_1_1_finalization_composite.html", "classsgns_1_1verification_1_1finality_1_1_finalization_composite" ],
          [ "FinalizationObserver", "classsgns_1_1verification_1_1finality_1_1_finalization_observer.html", "classsgns_1_1verification_1_1finality_1_1_finalization_observer" ],
          [ "Gossiper", "structsgns_1_1verification_1_1finality_1_1_gossiper.html", "structsgns_1_1verification_1_1finality_1_1_gossiper" ],
          [ "ObserverDummy", "classsgns_1_1verification_1_1finality_1_1_observer_dummy.html", "classsgns_1_1verification_1_1finality_1_1_observer_dummy" ],
          [ "RoundObserver", "structsgns_1_1verification_1_1finality_1_1_round_observer.html", "structsgns_1_1verification_1_1finality_1_1_round_observer" ],
          [ "RoundState", "structsgns_1_1verification_1_1finality_1_1_round_state.html", "structsgns_1_1verification_1_1finality_1_1_round_state" ],
          [ "SignedMessage", "structsgns_1_1verification_1_1finality_1_1_signed_message.html", "structsgns_1_1verification_1_1finality_1_1_signed_message" ],
          [ "SyncingRoundObserver", "classsgns_1_1verification_1_1finality_1_1_syncing_round_observer.html", "classsgns_1_1verification_1_1finality_1_1_syncing_round_observer" ],
          [ "TotalWeight", "namespacesgns_1_1verification_1_1finality.html#structsgns_1_1verification_1_1finality_1_1_total_weight", "namespacesgns_1_1verification_1_1finality_structsgns_1_1verification_1_1finality_1_1_total_weight_dup" ],
          [ "VoteCryptoProvider", "classsgns_1_1verification_1_1finality_1_1_vote_crypto_provider.html", "classsgns_1_1verification_1_1finality_1_1_vote_crypto_provider" ],
          [ "VoteCryptoProviderImpl", "classsgns_1_1verification_1_1finality_1_1_vote_crypto_provider_impl.html", "classsgns_1_1verification_1_1finality_1_1_vote_crypto_provider_impl" ],
          [ "VoteGraph", "structsgns_1_1verification_1_1finality_1_1_vote_graph.html", "structsgns_1_1verification_1_1finality_1_1_vote_graph" ],
          [ "VoteGraphImpl", "classsgns_1_1verification_1_1finality_1_1_vote_graph_impl.html", "classsgns_1_1verification_1_1finality_1_1_vote_graph_impl" ],
          [ "VoteMessage", "structsgns_1_1verification_1_1finality_1_1_vote_message.html", "structsgns_1_1verification_1_1finality_1_1_vote_message" ],
          [ "VoterSet", "structsgns_1_1verification_1_1finality_1_1_voter_set.html", "structsgns_1_1verification_1_1finality_1_1_voter_set" ],
          [ "VoteTracker", "classsgns_1_1verification_1_1finality_1_1_vote_tracker.html", "classsgns_1_1verification_1_1finality_1_1_vote_tracker" ],
          [ "VoteTrackerImpl", "classsgns_1_1verification_1_1finality_1_1_vote_tracker_impl.html", "classsgns_1_1verification_1_1finality_1_1_vote_tracker_impl" ],
          [ "VoteWeight", "classsgns_1_1verification_1_1finality_1_1_vote_weight.html", "classsgns_1_1verification_1_1finality_1_1_vote_weight" ],
          [ "VotingRound", "structsgns_1_1verification_1_1finality_1_1_voting_round.html", "structsgns_1_1verification_1_1finality_1_1_voting_round" ],
          [ "VotingRoundImpl", "classsgns_1_1verification_1_1finality_1_1_voting_round_impl.html", "classsgns_1_1verification_1_1finality_1_1_voting_round_impl" ]
        ] ],
        [ "BlockExecutor", "classsgns_1_1verification_1_1_block_executor.html", "classsgns_1_1verification_1_1_block_executor" ],
        [ "BlockValidator", "classsgns_1_1verification_1_1_block_validator.html", "classsgns_1_1verification_1_1_block_validator" ],
        [ "Epoch", "structsgns_1_1verification_1_1_epoch.html", "structsgns_1_1verification_1_1_epoch" ],
        [ "EpochStorage", "structsgns_1_1verification_1_1_epoch_storage.html", "structsgns_1_1verification_1_1_epoch_storage" ],
        [ "EpochStorageImpl", "classsgns_1_1verification_1_1_epoch_storage_impl.html", "classsgns_1_1verification_1_1_epoch_storage_impl" ],
        [ "NextEpochDescriptor", "structsgns_1_1verification_1_1_next_epoch_descriptor.html", "structsgns_1_1verification_1_1_next_epoch_descriptor" ],
        [ "Production", "classsgns_1_1verification_1_1_production.html", "classsgns_1_1verification_1_1_production" ],
        [ "ProductionBlockHeader", "namespacesgns_1_1verification.html#structsgns_1_1verification_1_1_production_block_header", "namespacesgns_1_1verification_structsgns_1_1verification_1_1_production_block_header_dup" ],
        [ "ProductionBlockValidator", "classsgns_1_1verification_1_1_production_block_validator.html", "classsgns_1_1verification_1_1_production_block_validator" ],
        [ "ProductionGossiper", "structsgns_1_1verification_1_1_production_gossiper.html", "structsgns_1_1verification_1_1_production_gossiper" ],
        [ "ProductionImpl", "classsgns_1_1verification_1_1_production_impl.html", "classsgns_1_1verification_1_1_production_impl" ],
        [ "ProductionLottery", "structsgns_1_1verification_1_1_production_lottery.html", "structsgns_1_1verification_1_1_production_lottery" ],
        [ "ProductionLotteryImpl", "classsgns_1_1verification_1_1_production_lottery_impl.html", "classsgns_1_1verification_1_1_production_lottery_impl" ],
        [ "ProductionMeta", "namespacesgns_1_1verification.html#structsgns_1_1verification_1_1_production_meta", "namespacesgns_1_1verification_structsgns_1_1verification_1_1_production_meta_dup" ],
        [ "ProductionSynchronizer", "classsgns_1_1verification_1_1_production_synchronizer.html", "classsgns_1_1verification_1_1_production_synchronizer" ],
        [ "ProductionSynchronizerImpl", "classsgns_1_1verification_1_1_production_synchronizer_impl.html", "classsgns_1_1verification_1_1_production_synchronizer_impl" ],
        [ "Seal", "namespacesgns_1_1verification.html#structsgns_1_1verification_1_1_seal", "namespacesgns_1_1verification_structsgns_1_1verification_1_1_seal_dup" ],
        [ "SyncingProductionObserver", "classsgns_1_1verification_1_1_syncing_production_observer.html", "classsgns_1_1verification_1_1_syncing_production_observer" ]
      ] ],
      [ "AppDelegate", "classsgns_1_1_app_delegate.html", "classsgns_1_1_app_delegate" ],
      [ "bulk_pull", "classsgns_1_1bulk__pull.html", "classsgns_1_1bulk__pull" ],
      [ "bulk_pull_account", "classsgns_1_1bulk__pull__account.html", "classsgns_1_1bulk__pull__account" ],
      [ "bulk_push", "classsgns_1_1bulk__push.html", "classsgns_1_1bulk__push" ],
      [ "confirm_ack", "classsgns_1_1confirm__ack.html", "classsgns_1_1confirm__ack" ],
      [ "confirm_req", "classsgns_1_1confirm__req.html", "classsgns_1_1confirm__req" ],
      [ "daemon_config", "classsgns_1_1daemon__config.html", "classsgns_1_1daemon__config" ],
      [ "frontier_req", "classsgns_1_1frontier__req.html", "classsgns_1_1frontier__req" ],
      [ "inactive_node", "classsgns_1_1inactive__node.html", "classsgns_1_1inactive__node" ],
      [ "ipfs_lite_store", "classsgns_1_1ipfs__lite__store.html", "classsgns_1_1ipfs__lite__store" ],
      [ "is_shared_ptr", "structsgns_1_1is__shared__ptr.html", null ],
      [ "is_shared_ptr< std::shared_ptr< T > >", "structsgns_1_1is__shared__ptr_3_01std_1_1shared__ptr_3_01_t_01_4_01_4.html", null ],
      [ "is_smart_ptr", "structsgns_1_1is__smart__ptr.html", null ],
      [ "is_smart_ptr< std::shared_ptr< T > >", "structsgns_1_1is__smart__ptr_3_01std_1_1shared__ptr_3_01_t_01_4_01_4.html", null ],
      [ "is_smart_ptr< std::unique_ptr< T > >", "structsgns_1_1is__smart__ptr_3_01std_1_1unique__ptr_3_01_t_01_4_01_4.html", null ],
      [ "is_unique_ptr", "structsgns_1_1is__unique__ptr.html", null ],
      [ "is_unique_ptr< std::unique_ptr< T > >", "structsgns_1_1is__unique__ptr_3_01std_1_1unique__ptr_3_01_t_01_4_01_4.html", null ],
      [ "keepalive", "classsgns_1_1keepalive.html", "classsgns_1_1keepalive" ],
      [ "logging", "classsgns_1_1logging.html", "classsgns_1_1logging" ],
      [ "message", "classsgns_1_1message.html", "classsgns_1_1message" ],
      [ "message_header", "classsgns_1_1message__header.html", "classsgns_1_1message__header" ],
      [ "message_parser", "classsgns_1_1message__parser.html", "classsgns_1_1message__parser" ],
      [ "message_visitor", "classsgns_1_1message__visitor.html", "classsgns_1_1message__visitor" ],
      [ "network", "classsgns_1_1network.html", "classsgns_1_1network" ],
      [ "node", "classsgns_1_1node.html", "classsgns_1_1node" ],
      [ "node_config", "classsgns_1_1node__config.html", "classsgns_1_1node__config" ],
      [ "node_flags", "namespacesgns.html#classsgns_1_1node__flags", "namespacesgns_classsgns_1_1node__flags_dup" ],
      [ "node_id_handshake", "classsgns_1_1node__id__handshake.html", "classsgns_1_1node__id__handshake" ],
      [ "node_rpc_config", "classsgns_1_1node__rpc__config.html", "classsgns_1_1node__rpc__config" ],
      [ "publish", "classsgns_1_1publish.html", "classsgns_1_1publish" ],
      [ "telemetry_ack", "classsgns_1_1telemetry__ack.html", "classsgns_1_1telemetry__ack" ],
      [ "telemetry_cache_cutoffs", "classsgns_1_1telemetry__cache__cutoffs.html", "classsgns_1_1telemetry__cache__cutoffs" ],
      [ "telemetry_data", "classsgns_1_1telemetry__data.html", "classsgns_1_1telemetry__data" ],
      [ "telemetry_req", "classsgns_1_1telemetry__req.html", "classsgns_1_1telemetry__req" ],
      [ "Unused", "structsgns_1_1_unused.html", "structsgns_1_1_unused" ],
      [ "wallet", "classsgns_1_1wallet.html", null ],
      [ "wallet_store", "namespacesgns.html#classsgns_1_1wallet__store", null ],
      [ "wallets", "classsgns_1_1wallets.html", "classsgns_1_1wallets" ]
    ] ],
    [ "std", "namespacestd.html", [
      [ "back_insert_iterator< Buffer >", "classstd_1_1back__insert__iterator_3_01_buffer_01_4.html", "classstd_1_1back__insert__iterator_3_01_buffer_01_4" ],
      [ "hash< boost::asio::ip::address >", "structstd_1_1hash_3_01boost_1_1asio_1_1ip_1_1address_01_4.html", "structstd_1_1hash_3_01boost_1_1asio_1_1ip_1_1address_01_4" ],
      [ "hash< sgns::base::Blob< N > >", "structstd_1_1hash_3_01sgns_1_1base_1_1_blob_3_01_n_01_4_01_4.html", "structstd_1_1hash_3_01sgns_1_1base_1_1_blob_3_01_n_01_4_01_4" ],
      [ "hash< sgns::base::Buffer >", "structstd_1_1hash_3_01sgns_1_1base_1_1_buffer_01_4.html", "structstd_1_1hash_3_01sgns_1_1base_1_1_buffer_01_4" ],
      [ "hash< sgns::base::Wrapper< T, Tag > >", "structstd_1_1hash_3_01sgns_1_1base_1_1_wrapper_3_01_t_00_01_tag_01_4_01_4.html", "structstd_1_1hash_3_01sgns_1_1base_1_1_wrapper_3_01_t_00_01_tag_01_4_01_4" ],
      [ "hash<::sgns::endpoint >", "structstd_1_1hash_3_1_1sgns_1_1endpoint_01_4.html", "structstd_1_1hash_3_1_1sgns_1_1endpoint_01_4" ],
      [ "hash<::sgns::tcp_endpoint >", "structstd_1_1hash_3_1_1sgns_1_1tcp__endpoint_01_4.html", "structstd_1_1hash_3_1_1sgns_1_1tcp__endpoint_01_4" ]
    ] ],
    [ "blake2b_ctx", "blake2b_8h.html#structblake2b__ctx", "blake2b_8h_structblake2b__ctx" ],
    [ "blake2s_ctx", "blake2s_8h.html#structblake2s__ctx", "blake2s_8h_structblake2s__ctx" ],
    [ "blake2s_ctx_full", "blake2s_8c.html#structblake2s__ctx__full", "blake2s_8c_structblake2s__ctx__full" ],
    [ "IPFS_val", "ipfs__lite__store_8hpp.html#struct_i_p_f_s__val", "ipfs__lite__store_8hpp_struct_i_p_f_s__val" ],
    [ "ProcessingTaskQueue", "class_processing_task_queue.html", "class_processing_task_queue" ],
    [ "sha3_context_", "keccak_8h.html#structsha3__context__", "keccak_8h_structsha3__context__" ],
    [ "sha3_context_.__unnamed3__", "keccak_8h.html#unionsha3__context___8____unnamed3____", "keccak_8h_unionsha3__context___8____unnamed3____" ],
    [ "SuperGenius", "namespace_3global_scope_4.html#class_super_genius", null ],
    [ "SuperGenius_OpenAPIImpl", "class_super_genius___open_a_p_i_impl.html", "class_super_genius___open_a_p_i_impl" ],
    [ "Unreachable_At_Line", "unreachable_8hpp.html#class_unreachable___at___line", null ]
];