add_subdirectory(account)
add_subdirectory(archive_node)
add_subdirectory(account_creation)
add_subdirectory(base)
add_subdirectory(bitswap)
add_subdirectory(mock)
add_subdirectory(multisig)
add_subdirectory(securecrdt)
add_subdirectory(peerregistry)
add_subdirectory(trustedpeer)
add_subdirectory(bridge_e2e)
add_subdirectory(startup)
add_subdirectory(blockchain)
add_subdirectory(crdt)
add_subdirectory(crypto)
add_subdirectory(graphsync)
add_subdirectory(local_secure_storage)
add_subdirectory(multiaccount)
add_subdirectory(node)
add_subdirectory(price_retrieval)
add_subdirectory(processing)
add_subdirectory(processing_datatypes)
add_subdirectory(processing_nodes)
add_subdirectory(processing_schema)
add_subdirectory(proof)
add_subdirectory(pubsub_counts)
add_subdirectory(storage)
add_subdirectory(transaction_sync)
add_subdirectory(watcher)
add_subdirectory(bridge_race)
