add_subdirectory(account_creation)
add_subdirectory(account)
add_subdirectory(authorship)
add_subdirectory(base)
add_subdirectory(blockchain)
add_subdirectory(crdt)
add_subdirectory(crypto)
add_subdirectory(graphsync)
add_subdirectory(local_secure_storage)
add_subdirectory(multiaccount)
add_subdirectory(price_retrieval)
add_subdirectory(primitives)
add_subdirectory(processing_nodes)
add_subdirectory(processing)
add_subdirectory(pubsub_counts)
add_subdirectory(scale)
add_subdirectory(storage)
add_subdirectory(transaction_sync)
add_subdirectory(verification)
add_subdirectory(watcher)
if (BUILD_WITH_PROOFS)
    add_subdirectory(proof)
endif()
