
#ifndef SUPERGENIUS_SRC_VERIFICATION_FINALITY_IMPL_VOTING_ROUND_ERROR_HPP
#define SUPERGENIUS_SRC_VERIFICATION_FINALITY_IMPL_VOTING_ROUND_ERROR_HPP

#include "outcome/outcome.hpp"

namespace sgns::verification::finality {

  enum class VotingRoundError {
    FIN_VALIDATION_FAILED = 1,
    LAST_ESTIMATE_BETTER_THAN_PREVOTE,
    NEW_STATE_EQUAL_TO_OLD,
  };

}

OUTCOME_HPP_DECLARE_ERROR_2(sgns::verification::finality, VotingRoundError);

#endif  // SUPERGENIUS_SRC_VERIFICATION_FINALITY_IMPL_VOTING_ROUND_ERROR_HPP
