/**
 * Hermetic price-retrieval integration suite (Phase 4, TEST-05, D-10/D-11/D-13).
 *
 * Drives the REAL wired path — GeniusNode::GetCoinprice — against one
 * HttpStubServer serving BOTH price tiers via distinct scripted paths
 * (/api/v3/simple/price CoinGecko shape, /v1/prices Phase 1 envelope shape).
 * Env vars redirect both tiers to the stub before GeniusNode::New, proving
 * env-redirect -> lazy manager -> node seam -> fallback tiers end-to-end
 * with zero live network.
 *
 * Replaces the old deliberately-unregistered live CoinGecko smoke suite
 * (current-price case superseded by HappyPathServesCoinGeckoShape; the two
 * historical-endpoint tests were deleted with the retriever per D-09).
 */
#include <gtest/gtest.h>

#include <atomic>
#include <chrono>
#include <memory>
#include <string>
#include <vector>

#include <boost/dll/runtime_symbol_info.hpp>
#include <boost/filesystem.hpp>

#include "account/GeniusAccount.hpp"
#include "account/GeniusNode.hpp"
#include "blockchain/Blockchain.hpp"
#include "local_secure_storage/impl/MemorySecureStorage.hpp"
#include "HttpStubServer.hpp"
#include "testutil/local_trust_setup.hpp"
#include "testutil/offline_chainlist.hpp"
#include "testutil/remove_all.hpp"
#include "testutil/scoped_env.hpp"

using namespace sgns::test;

namespace
{
    sgns::TokenID TOKEN_ID = sgns::TokenID::FromBytes( { 0x00 } );

    std::shared_ptr<sgns::GeniusAccount> WriteTrustedNodeConfig( const boost::filesystem::path &path,
                                                                 const char                    *private_key,
                                                                 const char                    *node_type,
                                                                 bool                           is_processor )
    {
        auto account = sgns::GeniusAccount::NewFromPrivateKey( TOKEN_ID, private_key, path );
        if ( !account )
        {
            return nullptr;
        }
        const auto address = account->GetAddress();
        sgns::test::WriteTrustedSgnsConfig( path, node_type, is_processor, false, { address }, address, 1, 1, 144 );
        return account;
    }

    void ConfirmConfiguredTrust( const std::shared_ptr<sgns::GeniusNode> &node )
    {
        ASSERT_NO_FATAL_FAILURE( sgns::test::MakeNodeReadyWithLocalTrust( node ) );
    }

    // Byte-real CloudFront 403 HTML (copied verbatim from price_facade_test.cpp).
    const char *kCloudFront403 =
        "<!DOCTYPE html><html><body><h1>403 ERROR</h1><p>ERROR: The request could not be "
        "satisfied</p><p>Generated by cloudfront (CloudFront)</p></body></html>";

    // Default tier-1 script: CoinGecko /simple/price 200 shape.
    const char *kCoinGeckoBody = R"({"genius-ai":{"usd":0.19},"bitcoin":{"usd":61234.12}})";

    // Default tier-2 script: Phase 1 /v1/prices envelope shape (byte-real
    // fixture values per the Phase 1 worker tests).
    const char *kEnvelopeBody =
        R"({"currency":"usd","prices":{"genius-ai":0.21,"bitcoin":61234.5},"fetchedAt":1790719217,"age":17,"source":"coingecko-cache","stale":false})";
} // namespace

/**
 * @brief Full-node integration fixture with hermetic price redirection.
 *
 * Ctor/dtor ordering (NOT SetUp/TearDown): the env value embeds the stub's
 * OS-assigned port, so the stub must Start first; env must be set before
 * GeniusNode::New (D-03); gtest constructs a fresh fixture per TEST_F, so
 * every scenario gets a fresh stub, fresh env, fresh node, and fresh lazy
 * manager — no L1/hold-off carryover between scenarios.
 */
class PriceRetrievalIntegrationTest : public ::testing::Test
{
public:
    // Unique per-test data dir (account-suite pattern) — must not collide with
    // the account suite's am_full_node_* directories.
    static inline std::atomic<uint64_t> next_test_index{ 0 };
    boost::filesystem::path             path = boost::dll::program_location().parent_path() /
                  ( "price_retrieval_node_" + std::to_string( next_test_index.fetch_add( 1 ) ) );

    PriceRetrievalIntegrationTest()
    {
        // (1) Script both tiers on ONE stub (D-11 — query strings are stripped
        // by the stub when matching, so path-only keys serve both request
        // shapes) and start it: the port must exist before the env value does.
        stub_.OnPath( "/api/v3/simple/price", { 200, "application/json", kCoinGeckoBody } );
        stub_.OnPath( "/v1/prices",           { 200, "application/json", kEnvelopeBody } );
        stub_.Start();

        // (2) Redirect both price tiers to the stub (plain http:// per D-04 —
        // the scheme in the URL decides transport security).
        const auto base = "http://127.0.0.1:" + std::to_string( stub_.Port() );
        envCoinGecko_ = std::make_unique<sgns::testutil::ScopedEnvVar>( "SGNS_COINGECKO_URL", base );
        envFallback_  = std::make_unique<sgns::testutil::ScopedEnvVar>( "SGNS_PRICE_FALLBACK_URL", base );

        // (3) The account suite's proven full-node bootstrap, verbatim in
        // sequence (env is already set — the lazy manager reads it at the
        // FIRST price call, and New does not construct one).
        sgns::test::removeAllWithRetry( path.string() );
        boost::filesystem::create_directories( path );
        sgns::GeniusNode::WriteNetworkConfig( path.generic_string() + '/', /*port_seed=*/0, /*auto_dht=*/false );
        sgns::GeniusAccount::SetSecureStorageFactory(
            []( const std::string &identifier ) -> std::shared_ptr<sgns::ISecureStorage>
            { return std::make_shared<sgns::MemorySecureStorage>( identifier ); } );

        const auto bootstrapper = WriteTrustedNodeConfig(
            path, "90bd26f57e3c243358666f32ff8321181545f4ddd8c981aceac163f26b05eaaa", "Full", true );
        assert( bootstrapper );
        sgns::Blockchain::SetAuthorizedFullNodeAddress( bootstrapper->GetAddress() );

        node_ = sgns::GeniusNode::New(
            { "0xcafe", "0.35", "1.0", TOKEN_ID, path.generic_string() + '/' },
            sgns::FromPrivateKey{ "90bd26f57e3c243358666f32ff8321181545f4ddd8c981aceac163f26b05eaaa" } );
        node_->SetChainlistFetcher( sgns::test::OfflineChainlistFetcher() );
        assert( node_ != nullptr );
        ConfirmConfiguredTrust( node_ );
        assert( node_->GetState() == sgns::GeniusNode::NodeState::READY );
    }

    ~PriceRetrievalIntegrationTest() override
    {
        // node_ released first (natural shared_ptr destruction — ~GeniusNode
        // resets the manager per 04-01); then env guards restore exact prior
        // state; then the stub stops.
        node_.reset();
        envCoinGecko_.reset();
        envFallback_.reset();
        stub_.Shutdown();
    }

    std::shared_ptr<sgns::GeniusNode> node_;

    sgns::testutil::HttpStubServer                stub_;
    std::unique_ptr<sgns::testutil::ScopedEnvVar> envCoinGecko_;
    std::unique_ptr<sgns::testutil::ScopedEnvVar> envFallback_;
};

// D-07 partial-map semantics through the real seam: both scripted prices
// served; an unknown id is absent yet the call still succeeds.
TEST_F( PriceRetrievalIntegrationTest, HappyPathServesCoinGeckoShape )
{
    auto result = node_->GetCoinprice( { "genius-ai", "bitcoin", "no-such-token" } );
    ASSERT_TRUE( result );
    const auto &prices = result.value();
    ASSERT_EQ( prices.size(), size_t{ 2 } );
    EXPECT_DOUBLE_EQ( prices.at( "genius-ai" ), 0.19 );
    EXPECT_DOUBLE_EQ( prices.at( "bitcoin" ), 61234.12 );
    EXPECT_EQ( prices.count( "no-such-token" ), size_t{ 0 } ); // absent, not error
}

// Tier 1 WAF-blocked before any L1 warm-up: the seam still serves via the
// tier-2 token.gnus.ai envelope (D-13 chain, fresh-manager leg).
TEST_F( PriceRetrievalIntegrationTest, Tier1BlockedFallsBackToTier2Envelope )
{
    stub_.OnPath( "/api/v3/simple/price", { 403, "text/html", kCloudFront403 } );
    auto result = node_->GetCoinprice( { "genius-ai" } );
    ASSERT_TRUE( result );
    EXPECT_DOUBLE_EQ( result.value().at( "genius-ai" ), 0.21 ); // tier-2 envelope value
}

// D-13 warm-then-fail: after tier 1 warms the L1, a 403 flip must still
// leave GetCoinprice serving — from the fresh L1 (within the 60s window)
// or tier 2. This is the milestone Core Value through the node seam.
TEST_F( PriceRetrievalIntegrationTest, WarmThenFailServesFreshL1 )
{
    auto warm = node_->GetCoinprice( { "genius-ai" } );
    ASSERT_TRUE( warm );
    EXPECT_DOUBLE_EQ( warm.value().at( "genius-ai" ), 0.19 ); // tier 1 served, L1 warmed

    stub_.OnPath( "/api/v3/simple/price", { 403, "text/html", kCloudFront403 } );
    auto after = node_->GetCoinprice( { "genius-ai" } );
    ASSERT_TRUE( after );
    // Fresh-L1 hit within the 60s window serves the warmed tier-1 value.
    EXPECT_DOUBLE_EQ( after.value().at( "genius-ai" ), 0.19 );
}

// 429 on tier 1 before any call: tier 2 serves; a second call still
// succeeds (the 429 hold-off on tier 1 does not hard-fail the seam —
// served from L1 or tier 2).
TEST_F( PriceRetrievalIntegrationTest, RateLimitedTierStillServes )
{
    stub_.OnPath( "/api/v3/simple/price", { 429, "text/html", "Too Many Requests" } );
    auto first = node_->GetCoinprice( { "genius-ai" } );
    ASSERT_TRUE( first );
    EXPECT_DOUBLE_EQ( first.value().at( "genius-ai" ), 0.21 ); // tier-2 envelope

    auto second = node_->GetCoinprice( { "genius-ai" } );
    ASSERT_TRUE( second );
    EXPECT_GT( second.value().at( "genius-ai" ), 0.0 ); // L1 or tier 2 — either way served
}

// Seam contract preserved (Pitfall 3): empty ids -> success with an empty
// map (would be an EmptyInput failure if propagated naively from
// GetQuotes({})).
TEST_F( PriceRetrievalIntegrationTest, EmptyIdsReturnsEmptyMap )
{
    auto result = node_->GetCoinprice( {} );
    ASSERT_TRUE( result );
    EXPECT_TRUE( result.value().empty() );
}
