#ifndef SUPERGENIUS_VERIFICATION_AUTHORITIES_UPDATE_OBSERVER_ERROR
#define SUPERGENIUS_VERIFICATION_AUTHORITIES_UPDATE_OBSERVER_ERROR

#include "outcome/outcome.hpp"

namespace sgns::authority {

  enum class AuthorityUpdateObserverError {
    UNSUPPORTED_MESSAGE_TYPE = 1,
    WRONG_AUTHORITY_INDEX,
    NO_SCHEDULED_CHANGE_APPLIED_YET,
    NO_FORCED_CHANGE_APPLIED_YET,
    NO_PAUSE_APPLIED_YET,
    NO_RESUME_APPLIED_YET,
  };

}  // namespace sgns::authority

OUTCOME_HPP_DECLARE_ERROR_2(sgns::authority, AuthorityUpdateObserverError)

#endif  // SUPERGENIUS_VERIFICATION_AUTHORITIES_UPDATE_OBSERVER_ERROR
