#include <gtest/gtest.h>
#include <boost/asio.hpp>
#include <chrono>
#include <memory>
#include <string>
#include <vector>

#include "HttpStubServer.hpp"
#include <coinprices/PriceHttpClient.hpp>
#include <coinprices/PriceQuote.hpp>
#include <coinprices/PriceFetchError.hpp>
#include <coinprices/PriceRetryPolicy.hpp>
#include <HTTPTypes.hpp>

namespace
{
    sgns::RetryConfig ZeroBackoffConfig()
    {
        sgns::RetryConfig config;
        config.backoffBeforeRetry = { std::chrono::milliseconds( 0 ),
                                      std::chrono::milliseconds( 0 ),
                                      std::chrono::milliseconds( 0 ) };
        return config;
    }

    const char *kGoodBody = R"({"genius-ai":{"usd":0.19},"bitcoin":{"usd":61234.12}})";
    const char *kCloudFront403 =
        "<!DOCTYPE html><html><body><h1>403 ERROR</h1><p>ERROR: The request could not be "
        "satisfied</p><p>Generated by cloudfront (CloudFront)</p></body></html>";
} // namespace

class PriceFacadeTest : public ::testing::Test
{
protected:
    static void SetUpTestSuite() {}
    static void TearDownTestSuite() {}

    void SetUp() override
    {
        stub_.Start();
    }

    void TearDown() override
    {
        stub_.Shutdown();
    }

    sgns::testutil::HttpStubServer stub_;

    std::shared_ptr<boost::asio::io_context> NewIoc()
    {
        return std::make_shared<boost::asio::io_context>();
    }

    sgns::PriceHttpClient NewClient( sgns::RetryConfig config = ZeroBackoffConfig() )
    {
        return sgns::PriceHttpClient( "http://127.0.0.1:" + std::to_string( stub_.Port() ), config );
    }
};

TEST_F( PriceFacadeTest, Ok200ProducesQuotesWithD14Fields )
{
    stub_.OnPath( "/api/v3/simple/price", { 200, "application/json", kGoodBody } );
    auto  client = NewClient();
    auto  result = client.FetchPrices( NewIoc(), { "genius-ai", "bitcoin" }, "usd" );
    ASSERT_TRUE( result );
    const auto &quotes = result.value();
    ASSERT_EQ( quotes.size(), size_t{ 2 } );
    EXPECT_EQ( quotes[0].asset, "genius-ai" );
    EXPECT_EQ( quotes[0].currency, "usd" );
    EXPECT_DOUBLE_EQ( quotes[0].price, 0.19 );
    EXPECT_EQ( quotes[0].source, sgns::PriceSource::CoinGecko );
    EXPECT_FALSE( quotes[0].stale );
    const auto age = std::chrono::system_clock::now() - quotes[0].timestamp;
    EXPECT_LT( age, std::chrono::seconds( 5 ) ); // D-14: fetch time ~ now
    EXPECT_DOUBLE_EQ( quotes[1].price, 61234.12 );
    EXPECT_EQ( client.AttemptsLastFetch(), 1 );
}

TEST_F( PriceFacadeTest, Blocked403FailsImmediatelyWithStatus )
{
    stub_.OnPath( "/api/v3/simple/price", { 403, "text/html", kCloudFront403 } );
    auto  client = NewClient();
    auto  result = client.FetchPrices( NewIoc(), { "genius-ai" }, "usd" );
    ASSERT_FALSE( result );
    EXPECT_EQ( result.error().code, sgns::PriceFetchError::Blocked );
    EXPECT_EQ( result.error().httpStatus, unsigned{ 403 } );
    EXPECT_NE( result.error().Message().find( "403" ), std::string::npos );
    EXPECT_NE( result.error().Message().find( "blocked" ), std::string::npos );
    EXPECT_EQ( client.AttemptsLastFetch(), 1 ); // never retried
}

TEST_F( PriceFacadeTest, RateLimited429FailsAndArmsHoldOff )
{
    stub_.OnPath( "/api/v3/simple/price", { 429, "text/html", "Too Many Requests" } );
    auto  client = NewClient();
    auto  result = client.FetchPrices( NewIoc(), { "genius-ai" }, "usd" );
    ASSERT_FALSE( result );
    EXPECT_EQ( result.error().code, sgns::PriceFetchError::RateLimitExceeded );
    EXPECT_EQ( result.error().httpStatus, unsigned{ 429 } );
    EXPECT_EQ( client.AttemptsLastFetch(), 1 ); // never retried
}

TEST_F( PriceFacadeTest, HeldOffTierSkipsNetworkEntirely )
{
    stub_.OnPath( "/api/v3/simple/price", { 429, "text/html", "Too Many Requests" } );
    auto  client = NewClient();
    // Arm the hold-off via a first 429 fetch
    auto  first = client.FetchPrices( NewIoc(), { "genius-ai" }, "usd" );
    ASSERT_FALSE( first );

    // Now re-script the stub to serve good data — a held-off client must
    // still refuse to hit the network; the good script would produce SUCCESS
    // if any request leaked through.
    stub_.OnPath( "/api/v3/simple/price", { 200, "application/json", kGoodBody } );
    auto second = client.FetchPrices( NewIoc(), { "genius-ai" }, "usd" );
    ASSERT_FALSE( second );
    EXPECT_EQ( second.error().code, sgns::PriceFetchError::RateLimitExceeded );
    EXPECT_EQ( second.error().httpStatus, unsigned{ 429 } );
}

TEST_F( PriceFacadeTest, TimeoutRetriesToCapThree )
{
    stub_.OnPath( "/api/v3/simple/price",
                  { 200, "application/json", "{}", std::chrono::milliseconds( 3000 ) } );
    sgns::PriceHttpClient client( "http://127.0.0.1:" + std::to_string( stub_.Port() ),
                                  ZeroBackoffConfig(),
                                  std::chrono::seconds( 60 ),
                                  [] { return std::chrono::system_clock::now(); },
                                  std::chrono::milliseconds( 300 ) ); // short read timeout
    auto result = client.FetchPrices( NewIoc(), { "genius-ai" }, "usd" );
    ASSERT_FALSE( result );
    EXPECT_EQ( result.error().code, sgns::PriceFetchError::NetworkError );
    EXPECT_EQ( result.error().httpStatus, unsigned{ 0 } );
    EXPECT_EQ( client.AttemptsLastFetch(), 3 ); // cap, no fourth
}

TEST_F( PriceFacadeTest, ParseErrorOnlyOn200Path )
{
    stub_.OnPath( "/api/v3/simple/price", { 200, "application/json", "not json" } );
    auto  client = NewClient();
    auto  result = client.FetchPrices( NewIoc(), { "genius-ai" }, "usd" );
    ASSERT_FALSE( result );
    EXPECT_EQ( result.error().code, sgns::PriceFetchError::JsonParseError );
    EXPECT_EQ( result.error().httpStatus, unsigned{ 200 } ); // parse errors occur ON the 200 path
}

TEST_F( PriceFacadeTest, MissingIdIsPartialCoverageNotError )
{
    stub_.OnPath( "/api/v3/simple/price", { 200, "application/json", R"({"bitcoin":{"usd":1}})" } );
    auto  client = NewClient();
    auto  result = client.FetchPrices( NewIoc(), { "genius-ai", "bitcoin" }, "usd" );
    ASSERT_TRUE( result );
    ASSERT_EQ( result.value().size(), size_t{ 1 } );
    EXPECT_EQ( result.value()[0].asset, "bitcoin" );
}

TEST_F( PriceFacadeTest, NoDataAtAllIsNoDataFound )
{
    stub_.OnPath( "/api/v3/simple/price", { 200, "application/json", R"({"other":{"usd":1}})" } );
    auto  client = NewClient();
    auto  result = client.FetchPrices( NewIoc(), { "genius-ai" }, "usd" );
    ASSERT_FALSE( result );
    EXPECT_EQ( result.error().code, sgns::PriceFetchError::NoDataFound );
}

TEST_F( PriceFacadeTest, UserAgentIsTheCoinGeckoFriendlyOne )
{
    stub_.OnPath( "/api/v3/simple/price", { 200, "application/json", kGoodBody } );
    auto  client = NewClient();
    auto  result = client.FetchPrices( NewIoc(), { "genius-ai" }, "usd" );
    ASSERT_TRUE( result );
    EXPECT_EQ( stub_.LastUserAgent( "/api/v3/simple/price" ), std::string( sgns::PriceHttpClient::kUserAgent ) );
}

// ---- Policy unit cases (Task 2 behaviors, hermetic) ----

TEST( PriceRetryPolicyTest, IsTransientTruthTable )
{
    using E = sgns::PriceFetchError;
    using C = sgns::http::ClientError;
    const std::vector<std::pair<sgns::PriceFetchFailure, bool>> cases = {
        // D-14: {NetworkError, 0} rows carry transport classifications —
        // strict gating delegates to IsTransientTransport.
        { { E::NetworkError, 0, C::TIMEOUT }, true },
        { { E::NetworkError, 0, C::CONNECT_FAILED }, true },
        { { E::NetworkError, 0, C::RESOLVE_FAILED }, true },
        // Permanent transport classes are never transient (D-14 core claim).
        { { E::NetworkError, 0, C::TLS_HANDSHAKE_FAILED }, false },
        { { E::NetworkError, 0, C::TLS_CA_LOAD_FAILED }, false },
        { { E::NetworkError, 0, C::WRITE_FAILED }, false },
        { { E::NetworkError, 0, C::READ_INTERRUPTED }, false },
        // Unclassified {NetworkError, 0} is NOT transient (strict).
        { { E::NetworkError, 0 }, false },
        { { E::Blocked, 403 }, false },
        { { E::RateLimitExceeded, 429 }, false },
        { { E::HttpStatus, 404 }, false },
        { { E::HttpStatus, 500 }, false },
        { { E::HttpStatus, 502 }, false },
        { { E::JsonParseError, 200 }, false },
        { { E::EmptyInput, 0 }, false },
        { { E::NoDataFound, 200 }, false },
    };
    for ( const auto &[failure, expected] : cases )
    {
        EXPECT_EQ( sgns::IsTransient( failure ), expected ) << failure.Message();
    }
}

TEST( PriceRetryPolicyTest, ShouldRetryCapsAtThreeForTransient )
{
    sgns::RetryConfig config; // defaults: 3 attempts
    const sgns::PriceFetchFailure transient{ sgns::PriceFetchError::NetworkError, 0, sgns::http::ClientError::TIMEOUT };
    EXPECT_EQ( sgns::ShouldRetry( transient, 1, config ), sgns::RetryDecision::Retry );
    EXPECT_EQ( sgns::ShouldRetry( transient, 2, config ), sgns::RetryDecision::Retry );
    EXPECT_EQ( sgns::ShouldRetry( transient, 3, config ), sgns::RetryDecision::GiveUp ); // no 4th
}

TEST( PriceRetryPolicyTest, ShouldRetryNeverRetriesStatusBearing )
{
    sgns::RetryConfig config;
    const sgns::PriceFetchFailure blocked{ sgns::PriceFetchError::Blocked, 403 };
    const sgns::PriceFetchFailure limited{ sgns::PriceFetchError::RateLimitExceeded, 429 };
    EXPECT_EQ( sgns::ShouldRetry( blocked, 1, config ), sgns::RetryDecision::GiveUp );
    EXPECT_EQ( sgns::ShouldRetry( limited, 1, config ), sgns::RetryDecision::GiveUp );
}

TEST( PriceRetryPolicyTest, RateLimitHoldOffWithInjectableClock )
{
    auto       now = std::chrono::system_clock::time_point{} + std::chrono::hours( 1000 );
    auto       nowFn = [&now]() { return now; };
    sgns::RateLimitHoldOff holdOff( nowFn );

    EXPECT_FALSE( holdOff.IsHeldOff() ); // before any trigger
    holdOff.TriggerHoldOff( std::chrono::seconds( 60 ) );
    EXPECT_TRUE( holdOff.IsHeldOff() );
    now += std::chrono::seconds( 59 );
    EXPECT_TRUE( holdOff.IsHeldOff() );
    now += std::chrono::seconds( 2 ); // 61s total
    EXPECT_FALSE( holdOff.IsHeldOff() );

    // Re-triggerable: a second trigger re-arms from the new now
    holdOff.TriggerHoldOff( std::chrono::seconds( 60 ) );
    EXPECT_TRUE( holdOff.IsHeldOff() );
}

TEST( PriceFetchErrorTest, MessageEmbedsStatus )
{
    sgns::PriceFetchFailure blocked{ sgns::PriceFetchError::Blocked, 403 };
    EXPECT_NE( blocked.Message().find( "403" ), std::string::npos );
    EXPECT_NE( blocked.Message().find( "blocked" ), std::string::npos );

    sgns::PriceFetchFailure limited{ sgns::PriceFetchError::RateLimitExceeded, 429 };
    EXPECT_NE( limited.Message().find( "429" ), std::string::npos );

    sgns::PriceFetchFailure plain{ sgns::PriceFetchError::NetworkError, 0 };
    EXPECT_EQ( plain.Message(), "Network Error" );

    sgns::PriceFetchFailure def;
    EXPECT_EQ( def.httpStatus, unsigned{ 0 } );
}

TEST( PriceFetchErrorTest, EnumeratorsPreserveLegacyOrder )
{
    using E = sgns::PriceFetchError;
    EXPECT_EQ( static_cast<int>( E::EmptyInput ), 1 );
    EXPECT_EQ( static_cast<int>( E::NetworkError ), 2 );
    EXPECT_EQ( static_cast<int>( E::JsonParseError ), 3 );
    EXPECT_EQ( static_cast<int>( E::NoDataFound ), 4 );
    EXPECT_EQ( static_cast<int>( E::RateLimitExceeded ), 5 );
    EXPECT_EQ( static_cast<int>( E::DateTooOld ), 6 );
    EXPECT_EQ( static_cast<int>( E::HttpStatus ), 7 );
    EXPECT_EQ( static_cast<int>( E::Blocked ), 8 );
}
